export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { brandName, activity, description, lang } = req.body || {};

  if (!brandName || !description) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  // The 7 strategic discovery stages. Each is generated by its own Anthropic
  // call and the calls run in parallel, so wall-clock time is the slowest single
  // stage (not the sum) — this keeps us well under the serverless time limit
  // even on Sonnet, which is slower than Haiku.
  const STAGE_SPECS = [
    { id: 's_why',         title_ar: 'لماذا الآن؟',                 title_en: 'Why now?',                       focus: 'The real trigger behind the rebrand, what has stopped working in the current brand, the cost of doing nothing, and what success looks like afterwards.' },
    { id: 's_audience',    title_ar: 'الجمهور والسوق',              title_en: 'Audience & market',              focus: 'Who the core audience really is, the main segments, an aspirational audience not yet reached, and where the brand sits in its market.' },
    { id: 's_competition', title_ar: 'المنافسة والتمايز',           title_en: 'Competition & differentiation',  focus: 'The competitive landscape, what genuinely sets this brand apart, and the unclaimed gap in the market it could own.' },
    { id: 's_gap',         title_ar: 'الفجوة الاستراتيجية',         title_en: 'The strategic gap',              focus: 'How the brand is perceived today versus how it wants to be perceived, its desired personality, and the emotional shift required.' },
    { id: 's_value',       title_ar: 'القيمة والوعد',               title_en: 'Value & promise',                focus: 'The core value proposition, the brand promise to customers, the key messages, and the reasons customers should believe them.' },
    { id: 's_equity',      title_ar: 'ما نحافظ عليه وما نتخلّص منه',  title_en: 'Keep & drop',                    focus: 'Which brand assets and equity must be protected, which elements should be dropped, and how recognizable the current brand already is.' },
    { id: 's_decision',    title_ar: 'القرار والقيود والرؤية',       title_en: 'Decision, constraints & vision', focus: 'Who the decision-makers are, any red lines or constraints, and the long-term vision for where the brand is heading.' }
  ];

  const tool = {
    name: 'submit_stage',
    description: 'Submit the generated brand-discovery questions for ONE stage',
    input_schema: {
      type: 'object',
      properties: {
        title_ar: { type: 'string' },
        title_en: { type: 'string' },
        questions: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              q_ar: { type: 'string' },
              q_en: { type: 'string' },
              type: { type: 'string', enum: ['multi', 'scale', 'textarea'] },
              options_ar: { type: 'array', items: { type: 'string' } },
              options_en: { type: 'array', items: { type: 'string' } },
              other: { type: 'boolean' },
              help_why_ar: { type: 'string' },
              help_why_en: { type: 'string' },
              help_ex_ar: { type: 'string' },
              help_ex_en: { type: 'string' },
              golden: { type: 'boolean' }
            },
            required: ['id', 'q_ar', 'q_en', 'type']
          }
        }
      },
      required: ['title_ar', 'title_en', 'questions']
    }
  };

  const arc = STAGE_SPECS.map((s, i) => (i + 1) + '. ' + s.title_en + ' (' + s.title_ar + ')').join(' | ');
  const langName = lang === 'en' ? 'English' : 'Arabic';

  const SYSTEM = "You are a Creative Director and brand strategist at Rabeez branding agency. You design brand-discovery questions that are deeply strategic: every question must surface an insight a strategist can later analyze to shape positioning, messaging, and visual direction — never generic or superficial. Tailor every question precisely to the client's industry. Do not ask for basic facts already on file (brand name, industry, founding year, contact details, social links); focus entirely on strategy. Arabic must be formal (فصحى) in the singular second-person voice. Generate exactly ONE stage with exactly 3 questions. For multi and scale questions provide options_ar and options_en as 4-5 matching items each; textarea questions take no options. Set golden:true on the single most strategically revealing question in the stage. Set other:true on every multi question. help_why_* states why the question matters strategically; help_ex_* gives a concrete example specific to the client's industry. Question ids must be unique. Always use the submit_stage tool.";

  async function genStage(spec, idx) {
    const userMsg = 'Client brand: ' + brandName + '\n'
      + 'Industry: ' + (activity || 'unspecified') + '\n'
      + 'In their own words: ' + description + '\n'
      + 'Primary language: ' + langName + '\n\n'
      + 'This brief has 7 strategic stages: ' + arc + '\n'
      + 'Generate ONLY stage ' + (idx + 1) + ' — "' + spec.title_en + '" (' + spec.title_ar + ').\n'
      + 'Focus of this stage: ' + spec.focus + '\n'
      + 'Use the exact stage titles title_ar="' + spec.title_ar + '" and title_en="' + spec.title_en + '". Prefix every question id with "' + spec.id + '_".';

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 2500,
        system: SYSTEM,
        tools: [tool],
        tool_choice: { type: 'tool', name: 'submit_stage' },
        messages: [{ role: 'user', content: userMsg }]
      })
    });

    if (!response.ok) {
      const detail = await response.text();
      throw new Error('Anthropic ' + response.status + ': ' + detail);
    }

    const data = await response.json();
    let toolInput = null;
    for (const block of data.content) {
      if (block.type === 'tool_use') { toolInput = block.input; break; }
    }
    if (!toolInput || !Array.isArray(toolInput.questions) || !toolInput.questions.length) {
      throw new Error('No tool output for stage ' + spec.id);
    }
    // Guarantee titles even if the model omitted them.
    toolInput.title_ar = toolInput.title_ar || spec.title_ar;
    toolInput.title_en = toolInput.title_en || spec.title_en;
    return { idx: idx, stage: toolInput };
  }

  // One retry per stage — a dropped stage leaves a visible gap in the form.
  async function genStageRetry(spec, idx) {
    try {
      return await genStage(spec, idx);
    } catch (e) {
      return await genStage(spec, idx);
    }
  }

  try {
    const settled = await Promise.allSettled(STAGE_SPECS.map((s, i) => genStageRetry(s, i)));
    const stages = settled
      .filter(function (r) { return r.status === 'fulfilled'; })
      .map(function (r) { return r.value; })
      .sort(function (a, b) { return a.idx - b.idx; })
      .map(function (r) { return r.stage; });

    if (!stages.length) {
      const firstErr = settled.find(function (r) { return r.status === 'rejected'; });
      return res.status(500).json({ error: 'Generation failed', detail: firstErr ? String(firstErr.reason) : 'unknown' });
    }

    return res.status(200).json({ stages: stages });

  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
