export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { brandName, activity, description, lang, only } = req.body || {};

  if (!brandName || !description) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  // The 7 strategic discovery stages. Each is generated by its own Anthropic
  // call and the calls run in parallel, so wall-clock time is the slowest single
  // stage (not the sum) — this keeps us well under the serverless time limit
  // even on Sonnet, which is slower than Haiku.
  const STAGE_SPECS = [
    { id: 's_why',         title_ar: 'لماذا الآن؟',                 title_en: 'Why now?',                       focus: 'The real trigger behind the rebrand, what has stopped working in the current brand, the cost of doing nothing, and what success looks like afterwards.' },
    { id: 's_audience',    title_ar: 'الجمهور والسوق',              title_en: 'Audience & market',              focus: 'Who the core audience really is, the main segments, an aspirational audience not yet reached, and where the brand sits in its market.' },
    { id: 's_competition', title_ar: 'المنافسة والتمايز',           title_en: 'Competition & differentiation',  focus: 'The competitive landscape, what genuinely sets this brand apart, and the unclaimed gap in the market it could own.' },
    { id: 's_gap',         title_ar: 'الفجوة الاستراتيجية',         title_en: 'The strategic gap',              focus: 'How the brand is perceived today versus how it wants to be perceived, its desired personality, and the emotional shift required.' },
    { id: 's_value',       title_ar: 'القيمة والوعد',               title_en: 'Value & promise',                focus: 'The core value proposition, the brand promise to customers, the key messages, and the reasons customers should believe them.' },
    { id: 's_equity',      title_ar: 'ما نحافظ عليه وما نتخلّص منه',  title_en: 'Keep & drop',                    focus: 'Which brand assets and equity must be protected, which elements should be dropped, and how recognizable the current brand already is.' },
    { id: 's_decision',    title_ar: 'القرار والقيود والرؤية',       title_en: 'Decision, constraints & vision', focus: 'Who the decision-makers are, any red lines or constraints, and the long-term vision for where the brand is heading.' }
  ];

  const tool = {
    name: 'submit_stage',
    description: 'Submit the generated brand-discovery questions for ONE stage',
    input_schema: {
      type: 'object',
      properties: {
        title_ar: { type: 'string' },
        title_en: { type: 'string' },
        questions: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              q_ar: { type: 'string' },
              q_en: { type: 'string' },
              type: { type: 'string', enum: ['multi', 'scale', 'textarea'] },
              options_ar: { type: 'array', items: { type: 'string' } },
              options_en: { type: 'array', items: { type: 'string' } },
              other: { type: 'boolean' },
              help_why_ar: { type: 'string' },
              help_why_en: { type: 'string' },
              help_ex_ar: { type: 'string' },
              help_ex_en: { type: 'string' },
              golden: { type: 'boolean' }
            },
            required: ['id', 'q_ar', 'q_en', 'type']
          }
        }
      },
      required: ['title_ar', 'title_en', 'questions']
    }
  };

  const arc = STAGE_SPECS.map((s, i) => (i + 1) + '. ' + s.title_en + ' (' + s.title_ar + ')').join(' | ');
  const langName = lang === 'en' ? 'English' : 'Arabic';

  const SYSTEM = "You are a Creative Director and brand strategist at Rabeez branding agency. You design brand-discovery questions that are deeply strategic: every question must surface an insight a strategist can later analyze to shape positioning, messaging, and visual direction — never generic or superficial. Tailor every question precisely to the client's industry. Do not ask for basic facts already on file (brand name, industry, founding year, contact details, social links).\n\nWORDING — keep it simple: phrase every question and every option in plain, everyday language that a busy business owner understands instantly. Use short, direct sentences and common words. No marketing jargon, no abstract strategist vocabulary, no compound or convoluted phrasing. The strategy lives in WHAT you ask, never in complicated wording. If a question needs re-reading to be understood, rewrite it more simply.\n\nARABIC QUALITY — must be flawless: all Arabic (questions, options, help text) is formal فصحى in the singular second-person voice, with perfect spelling and orthography (correct hamza ء/أ/إ/ئ/ؤ, تاء مربوطة vs هاء, ألف مقصورة vs ياء), sound grammar, and natural phrasing. Proofread every Arabic string before submitting — never output a word with a typo, a missing or extra letter, or a malformed word. Every option must be a real, complete, correctly spelled Arabic phrase.\n\nGenerate exactly ONE stage with exactly 3 questions. Keep every field tight and economical: each question is one sentence; help_why_* is a single short clause of at most 12 words. For multi and scale questions provide options_ar and options_en as exactly 4 matching items each; textarea questions take no options. Provide help_ex_* (one short concrete example, at most 20 words) ONLY for the single golden question, and omit help_ex entirely on the other two questions. Set golden:true on the single most strategically revealing question. Set other:true on every multi question. Question ids must be unique. Always use the submit_stage tool.";

  // Single attempt: one Anthropic call producing one stage.
  async function callStage(spec, idx) {
    const userMsg = 'Client brand: ' + brandName + '\n'
      + 'Industry: ' + (activity || 'unspecified') + '\n'
      + 'In their own words: ' + description + '\n'
      + 'Primary language: ' + langName + '\n\n'
      + 'This brief has 7 strategic stages: ' + arc + '\n'
      + 'Generate ONLY stage ' + (idx + 1) + ' — "' + spec.title_en + '" (' + spec.title_ar + ').\n'
      + 'Focus of this stage: ' + spec.focus + '\n'
      + 'Use the exact stage titles title_ar="' + spec.title_ar + '" and title_en="' + spec.title_en + '". Prefix every question id with "' + spec.id + '_".';

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 1500,
        system: SYSTEM,
        tools: [tool],
        tool_choice: { type: 'tool', name: 'submit_stage' },
        messages: [{ role: 'user', content: userMsg }]
      })
    });

    if (!response.ok) {
      const detail = await response.text();
      const err = new Error('Anthropic ' + response.status);
      err.status = response.status;
      const ra = parseFloat(response.headers.get('retry-after'));
      err.retryAfter = isNaN(ra) ? null : ra;
      err.detail = detail;
      throw err;
    }

    const data = await response.json();
    let toolInput = null;
    for (const block of data.content) {
      if (block.type === 'tool_use') { toolInput = block.input; break; }
    }
    if (!toolInput || !Array.isArray(toolInput.questions) || !toolInput.questions.length) {
      throw new Error('No tool output for stage ' + spec.id);
    }
    // Guarantee titles even if the model omitted them.
    toolInput.title_ar = toolInput.title_ar || spec.title_ar;
    toolInput.title_en = toolInput.title_en || spec.title_en;
    return { idx: idx, stage: toolInput };
  }

  // Up to two attempts per stage. On a 429 (OTPM exhausted) wait for the window
  // to refill before retrying — an instant retry just hits the same wall. Waits
  // are capped so the parallel batch still finishes inside the 60s budget.
  async function genStageRetry(spec, idx) {
    try {
      return await callStage(spec, idx);
    } catch (e) {
      const waitS = e.status === 429 ? Math.min(e.retryAfter || 6, 10) : 1.5;
      await new Promise(function (r) { setTimeout(r, waitS * 1000); });
      return await callStage(spec, idx);
    }
  }

  // Optional subset: `only` is an array of 0-based stage indices to generate.
  // This lets the client request stages in batches (progressive generation).
  const idxList = (Array.isArray(only) && only.length)
    ? only.filter(function (i) { return Number.isInteger(i) && i >= 0 && i < STAGE_SPECS.length; })
    : STAGE_SPECS.map(function (s, i) { return i; });

  try {
    const settled = await Promise.allSettled(idxList.map(function (i) { return genStageRetry(STAGE_SPECS[i], i); }));
    const stages = settled
      .filter(function (r) { return r.status === 'fulfilled'; })
      .map(function (r) { return r.value; })
      .sort(function (a, b) { return a.idx - b.idx; })
      .map(function (r) { r.stage._idx = r.idx; return r.stage; });

    if (!stages.length) {
      const firstErr = settled.find(function (r) { return r.status === 'rejected'; });
      return res.status(500).json({ error: 'Generation failed', detail: firstErr ? String(firstErr.reason) : 'unknown' });
    }

    return res.status(200).json({ stages: stages });

  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
